# add ~/.bash_profile if needed for executing ~/.bashrc
if [ -e ~/.bashrc -a ! -e ~/.bash_profile -a ! -e ~/.bash_login -a ! -e ~/.profile ]; then
  printf "\n\033[31mWARNING: Found ~/.bashrc but no ~/.bash_profile, ~/.bash_login or ~/.profile.\033[m\n\n"
  echo "This looks like an incorrect setup."
  echo "A ~/.bash_profile that loads ~/.bashrc will be created for you."
  cat >~/.bash_profile <<-\EOF
	# generated by Git for Windows
	test -f ~/.profile && . ~/.profile
	test -f ~/.bashrc && . ~/.bashrc
	EOF
fi

function co() {
	git commit -m "$1"
}

function s() {
	git status
}

function c() {
	git checkout $1
}

function a() {
	git add .
}

function r() {
	git reset --hard
}

function rc() {
	git reset --soft HEAD^
}

function cl() {
	git clean -fdx
}

function su() {
	git submodule update
}

function p() {
	git pull origin
}

function po() {
	git pull origin $1
}

function clone() {
	git clone $1
}

function e() {
	start .
}

function mobile() {
	start C:/Users/evgeni.r/dev/mobile/Mobile.sln
}

function i() {
	npm install
}

function bd() {
	npm run build:debug
}

function br() {
	npm run build:release
}

function watch() {
	npm run test -- $1 --watch
}